# Generated by Django 4.2.7 on 2025-11-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productimage_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon_file",
            field=models.ImageField(
                blank=True,
                help_text="上传本地图片作为分类图标",
                null=True,
                upload_to="categories/icons/",
                verbose_name="分类图标文件",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.URLField(
                blank=True,
                help_text="如果上传了图片文件，则优先使用图片文件",
                verbose_name="分类图标URL",
            ),
        ),
    ]
