# Generated by Django 4.2.7 on 2025-10-17 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "delivery_no",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="配送单号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待分配"),
                            ("assigned", "已分配"),
                            ("accepted", "已接单"),
                            ("picked_up", "已取货"),
                            ("delivering", "配送中"),
                            ("delivered", "已送达"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="配送状态",
                    ),
                ),
                ("delivery_address", models.TextField(verbose_name="配送地址")),
                (
                    "contact_name",
                    models.CharField(max_length=50, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="分配时间"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="接单时间"
                    ),
                ),
                (
                    "picked_up_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="取货时间"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送达时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="配送备注")),
            ],
            options={
                "verbose_name": "配送记录",
                "verbose_name_plural": "配送记录",
                "db_table": "delivery_delivery",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "phone",
                    models.CharField(max_length=20, unique=True, verbose_name="手机号"),
                ),
                (
                    "id_card",
                    models.CharField(
                        blank=True, max_length=18, verbose_name="身份证号"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "离线"), (1, "在线"), (2, "忙碌"), (3, "休假")],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="总订单数"),
                ),
                (
                    "completed_orders",
                    models.IntegerField(default=0, verbose_name="完成订单数"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, default=5.0, max_digits=3, verbose_name="评分"
                    ),
                ),
                (
                    "current_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="当前位置纬度",
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="当前位置经度",
                    ),
                ),
                (
                    "last_update_location",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后更新位置时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "配送员",
                "verbose_name_plural": "配送员",
                "db_table": "delivery_deliveryperson",
            },
        ),
        migrations.CreateModel(
            name="DeliveryTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("status", models.CharField(max_length=20, verbose_name="状态")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, verbose_name="地址"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="delivery.delivery",
                    ),
                ),
            ],
            options={
                "verbose_name": "配送轨迹",
                "verbose_name_plural": "配送轨迹",
                "db_table": "delivery_deliverytrack",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "rating",
                    models.SmallIntegerField(
                        choices=[
                            (1, "1星"),
                            (2, "2星"),
                            (3, "3星"),
                            (4, "4星"),
                            (5, "5星"),
                        ],
                        verbose_name="评分",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="评价内容")),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="delivery.delivery",
                    ),
                ),
                (
                    "delivery_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="delivery.deliveryperson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "配送评价",
                "verbose_name_plural": "配送评价",
                "db_table": "delivery_deliveryrating",
            },
        ),
        migrations.AddIndex(
            model_name="deliveryperson",
            index=models.Index(fields=["phone"], name="delivery_de_phone_092ac4_idx"),
        ),
        migrations.AddIndex(
            model_name="deliveryperson",
            index=models.Index(fields=["status"], name="delivery_de_status_c71c7b_idx"),
        ),
        migrations.AddIndex(
            model_name="deliveryperson",
            index=models.Index(
                fields=["is_active"], name="delivery_de_is_acti_9a3c17_idx"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="delivery.deliveryperson",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery",
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverytrack",
            index=models.Index(
                fields=["delivery", "created_at"], name="delivery_de_deliver_98ba2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryrating",
            index=models.Index(
                fields=["delivery"], name="delivery_de_deliver_149169_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryrating",
            index=models.Index(fields=["user"], name="delivery_de_user_id_f97320_idx"),
        ),
        migrations.AddIndex(
            model_name="deliveryrating",
            index=models.Index(
                fields=["delivery_person"], name="delivery_de_deliver_384852_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["delivery_no"], name="delivery_de_deliver_3209b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(fields=["order"], name="delivery_de_order_i_6d5362_idx"),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["delivery_person"], name="delivery_de_deliver_c9ce47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(fields=["status"], name="delivery_de_status_6efeaa_idx"),
        ),
    ]
