# Generated by Django 4.2.7 on 2025-10-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="city",
            field=models.CharField(blank=True, max_length=50, verbose_name="城市"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="detail_address",
            field=models.CharField(blank=True, max_length=200, verbose_name="详细地址"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="district",
            field=models.CharField(blank=True, max_length=50, verbose_name="区县"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="province",
            field=models.CharField(blank=True, max_length=50, verbose_name="省份"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="street",
            field=models.CharField(blank=True, max_length=100, verbose_name="街道"),
        ),
    ]
