# Generated by Django 4.2.7 on 2025-10-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cart",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="addresses.address",
                verbose_name="收货地址",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["address"], name="orders_cart_address_fac773_idx"
            ),
        ),
    ]
