# Generated by Django 4.2.7 on 2025-10-17 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="收货人姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="收货人电话")),
                ("province", models.CharField(max_length=50, verbose_name="省份")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                ("district", models.CharField(max_length=50, verbose_name="区县")),
                ("street", models.CharField(max_length=200, verbose_name="街道")),
                ("detail_address", models.TextField(verbose_name="详细地址")),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认地址"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户地址",
                "verbose_name_plural": "用户地址",
                "db_table": "addresses_address",
                "ordering": ["-is_default", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="addresses_a_user_id_b900c8_idx"
                    ),
                    models.Index(
                        fields=["longitude", "latitude"],
                        name="addresses_a_longitu_51ef1f_idx",
                    ),
                ],
            },
        ),
    ]
