# Generated by Django 4.2.7 on 2025-10-17 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="优惠券名称")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="优惠券描述"),
                ),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("discount", "折扣券"),
                            ("cash", "现金券"),
                            ("free_shipping", "免运费券"),
                        ],
                        max_length=20,
                        verbose_name="优惠券类型",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="优惠金额",
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="折扣率",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="最低消费金额",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最大优惠金额",
                    ),
                ),
                (
                    "total_count",
                    models.IntegerField(default=0, verbose_name="发放总数"),
                ),
                (
                    "used_count",
                    models.IntegerField(default=0, verbose_name="已使用数量"),
                ),
                (
                    "per_user_limit",
                    models.IntegerField(default=1, verbose_name="每用户限领数量"),
                ),
                ("valid_from", models.DateTimeField(verbose_name="有效期开始时间")),
                ("valid_to", models.DateTimeField(verbose_name="有效期结束时间")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "applicable_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="applicable_coupons",
                        to="products.category",
                    ),
                ),
                (
                    "applicable_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="applicable_coupons",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "优惠券",
                "verbose_name_plural": "优惠券",
                "db_table": "coupons_coupon",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unused", "未使用"),
                            ("used", "已使用"),
                            ("expired", "已过期"),
                        ],
                        default="unused",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                ("expired_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to="coupons.coupon",
                    ),
                ),
                (
                    "used_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_coupons",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户优惠券",
                "verbose_name_plural": "用户优惠券",
                "db_table": "coupons_usercoupon",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="优惠金额"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usages",
                        to="orders.order",
                    ),
                ),
                (
                    "user_coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="coupons.usercoupon",
                    ),
                ),
            ],
            options={
                "verbose_name": "优惠券使用记录",
                "verbose_name_plural": "优惠券使用记录",
                "db_table": "coupons_couponusage",
            },
        ),
        migrations.AddIndex(
            model_name="usercoupon",
            index=models.Index(
                fields=["user", "status"], name="coupons_use_user_id_aa902e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercoupon",
            index=models.Index(
                fields=["coupon"], name="coupons_use_coupon__dfe732_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercoupon",
            index=models.Index(
                fields=["expired_at"], name="coupons_use_expired_3f4e02_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercoupon",
            unique_together={("user", "coupon")},
        ),
        migrations.AddIndex(
            model_name="couponusage",
            index=models.Index(
                fields=["user_coupon"], name="coupons_cou_user_co_633ae8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="couponusage",
            index=models.Index(fields=["order"], name="coupons_cou_order_i_961167_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["coupon_type"], name="coupons_cou_coupon__d1f056_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["is_active"], name="coupons_cou_is_acti_a50634_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["valid_from", "valid_to"], name="coupons_cou_valid_f_cf442c_idx"
            ),
        ),
    ]
