# Generated by Django 4.2.7 on 2025-10-17 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "payment_no",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="支付单号"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("wechat", "微信支付"),
                            ("alipay", "支付宝"),
                            ("balance", "余额支付"),
                        ],
                        max_length=20,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="支付金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("failed", "支付失败"),
                            ("cancelled", "已取消"),
                            ("refunding", "退款中"),
                            ("refunded", "已退款"),
                            ("refund_failed", "退款失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "third_party_trade_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="第三方交易号"
                    ),
                ),
                (
                    "third_party_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="第三方响应数据"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "expired_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "支付记录",
                "verbose_name_plural": "支付记录",
                "db_table": "payments_payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="余额"
                    ),
                ),
                (
                    "frozen_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="冻结金额",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户余额",
                "verbose_name_plural": "用户余额",
                "db_table": "payments_userbalance",
            },
        ),
        migrations.CreateModel(
            name="BalanceTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "transaction_no",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="交易单号"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("recharge", "充值"),
                            ("consume", "消费"),
                            ("refund", "退款"),
                            ("freeze", "冻结"),
                            ("unfreeze", "解冻"),
                        ],
                        max_length=20,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="交易金额"
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="交易前余额"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="交易后余额"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                    ),
                ),
                (
                    "related_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "余额交易记录",
                "verbose_name_plural": "余额交易记录",
                "db_table": "payments_balancetransaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "refund_no",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="退款单号"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="退款金额"
                    ),
                ),
                ("reason", models.TextField(verbose_name="退款原因")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "退款中"),
                            ("success", "退款成功"),
                            ("failed", "退款失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="退款状态",
                    ),
                ),
                (
                    "third_party_refund_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="第三方退款号"
                    ),
                ),
                (
                    "third_party_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="第三方响应数据"
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退款时间"
                    ),
                ),
                (
                    "review_remark",
                    models.TextField(blank=True, verbose_name="审核备注"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewed_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "退款记录",
                "verbose_name_plural": "退款记录",
                "db_table": "payments_refund",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["refund_no"], name="payments_re_refund__76b026_idx"
                    ),
                    models.Index(
                        fields=["payment"], name="payments_re_payment_0f5ef3_idx"
                    ),
                    models.Index(
                        fields=["order"], name="payments_re_order_i_891133_idx"
                    ),
                    models.Index(
                        fields=["user"], name="payments_re_user_id_3d5301_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payments_re_status_715c3a_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_no"], name="payments_pa_payment_eb7d96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["order"], name="payments_pa_order_i_1d1c93_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["user"], name="payments_pa_user_id_be07d0_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_pa_status_7ad4af_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["third_party_trade_no"], name="payments_pa_third_p_bcb86d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="balancetransaction",
            index=models.Index(
                fields=["transaction_no"], name="payments_ba_transac_f59a67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="balancetransaction",
            index=models.Index(
                fields=["user", "created_at"], name="payments_ba_user_id_cbf95c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="balancetransaction",
            index=models.Index(
                fields=["transaction_type"], name="payments_ba_transac_d37b61_idx"
            ),
        ),
    ]
