# Generated by Django 4.2.7 on 2025-10-17 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日报"),
                            ("weekly", "周报"),
                            ("monthly", "月报"),
                            ("yearly", "年报"),
                        ],
                        max_length=20,
                        verbose_name="报表类型",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="报表日期")),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="总订单数"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="总销售额",
                    ),
                ),
                (
                    "total_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="总利润",
                    ),
                ),
                (
                    "new_customers",
                    models.IntegerField(default=0, verbose_name="新客户数"),
                ),
                (
                    "repeat_customers",
                    models.IntegerField(default=0, verbose_name="回头客数"),
                ),
                (
                    "top_products",
                    models.JSONField(blank=True, default=list, verbose_name="热销商品"),
                ),
                (
                    "top_categories",
                    models.JSONField(blank=True, default=list, verbose_name="热销分类"),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="平均订单价值",
                    ),
                ),
                (
                    "order_cancellation_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="订单取消率",
                    ),
                ),
            ],
            options={
                "verbose_name": "销售报表",
                "verbose_name_plural": "销售报表",
                "db_table": "analytics_salesreport",
                "ordering": ["-report_date"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "report_date"],
                        name="analytics_s_report__3e0d5f_idx",
                    )
                ],
                "unique_together": {("report_type", "report_date")},
            },
        ),
        migrations.CreateModel(
            name="ProductAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "total_views",
                    models.IntegerField(default=0, verbose_name="总浏览量"),
                ),
                (
                    "unique_views",
                    models.IntegerField(default=0, verbose_name="独立访客数"),
                ),
                (
                    "add_to_cart_count",
                    models.IntegerField(default=0, verbose_name="加入购物车次数"),
                ),
                (
                    "order_count",
                    models.IntegerField(default=0, verbose_name="订单数量"),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="转化率"
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(default=0, verbose_name="评价数量"),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="平均评分",
                    ),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后浏览时间"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品分析",
                "verbose_name_plural": "商品分析",
                "db_table": "analytics_productanalytics",
            },
        ),
        migrations.CreateModel(
            name="DailyStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                ("new_users", models.IntegerField(default=0, verbose_name="新增用户")),
                (
                    "active_users",
                    models.IntegerField(default=0, verbose_name="活跃用户"),
                ),
                (
                    "total_users",
                    models.IntegerField(default=0, verbose_name="总用户数"),
                ),
                ("new_orders", models.IntegerField(default=0, verbose_name="新增订单")),
                (
                    "paid_orders",
                    models.IntegerField(default=0, verbose_name="已支付订单"),
                ),
                (
                    "completed_orders",
                    models.IntegerField(default=0, verbose_name="已完成订单"),
                ),
                (
                    "cancelled_orders",
                    models.IntegerField(default=0, verbose_name="已取消订单"),
                ),
                (
                    "order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="订单金额",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="支付金额",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="退款金额",
                    ),
                ),
                (
                    "product_views",
                    models.IntegerField(default=0, verbose_name="商品浏览量"),
                ),
                (
                    "product_sales",
                    models.IntegerField(default=0, verbose_name="商品销量"),
                ),
            ],
            options={
                "verbose_name": "每日统计",
                "verbose_name_plural": "每日统计",
                "db_table": "analytics_dailystatistics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="analytics_d_date_1002f4_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBehavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "behavior_type",
                    models.CharField(
                        choices=[
                            ("page_view", "页面浏览"),
                            ("product_view", "商品浏览"),
                            ("add_to_cart", "加入购物车"),
                            ("remove_from_cart", "移除购物车"),
                            ("order_create", "创建订单"),
                            ("order_pay", "支付订单"),
                            ("order_cancel", "取消订单"),
                            ("search", "搜索"),
                            ("share", "分享"),
                            ("collect", "收藏"),
                        ],
                        max_length=20,
                        verbose_name="行为类型",
                    ),
                ),
                ("page_url", models.URLField(blank=True, verbose_name="页面URL")),
                (
                    "page_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="页面标题"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="额外数据"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_behaviors",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_behaviors",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behaviors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户行为",
                "verbose_name_plural": "用户行为",
                "db_table": "analytics_userbehavior",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "behavior_type"],
                        name="analytics_u_user_id_eee52f_idx",
                    ),
                    models.Index(
                        fields=["behavior_type"], name="analytics_u_behavio_6da99e_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_u_created_659b68_idx"
                    ),
                ],
            },
        ),
    ]
