# Generated by Django 4.2.7 on 2025-10-17 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="通知标题")),
                ("content", models.TextField(verbose_name="通知内容")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "系统通知"),
                            ("order", "订单通知"),
                            ("payment", "支付通知"),
                            ("delivery", "配送通知"),
                            ("promotion", "促销通知"),
                        ],
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "普通"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                ("related_url", models.URLField(blank=True, verbose_name="相关链接")),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="是否已发送"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发送时间"
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="计划发送时间"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="orders.order",
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("sms", "短信模板"),
                            ("wechat", "微信模板"),
                            ("email", "邮件模板"),
                            ("push", "推送模板"),
                        ],
                        max_length=20,
                        verbose_name="模板类型",
                    ),
                ),
                (
                    "title_template",
                    models.CharField(max_length=200, verbose_name="标题模板"),
                ),
                ("content_template", models.TextField(verbose_name="内容模板")),
                (
                    "variables",
                    models.JSONField(blank=True, default=dict, verbose_name="变量说明"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "通知模板",
                "verbose_name_plural": "通知模板",
                "db_table": "notifications_notificationtemplate",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["template_type"], name="notificatio_templat_5e0a58_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="notificatio_is_acti_b2a982_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="消息标题")),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("system", "系统消息"),
                            ("order", "订单消息"),
                            ("customer_service", "客服消息"),
                            ("marketing", "营销消息"),
                        ],
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
                "db_table": "notifications_message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("channel", models.CharField(max_length=20, verbose_name="发送渠道")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("sent", "已发送"),
                            ("failed", "发送失败"),
                            ("delivered", "已送达"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="发送状态",
                    ),
                ),
                (
                    "third_party_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="第三方ID"
                    ),
                ),
                (
                    "third_party_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="第三方响应"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发送时间"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送达时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="notifications.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "通知发送日志",
                "verbose_name_plural": "通知发送日志",
                "db_table": "notifications_notificationlog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["notification"], name="notificatio_notific_ca68c9_idx"
                    ),
                    models.Index(
                        fields=["user"], name="notificatio_user_id_9c973b_idx"
                    ),
                    models.Index(
                        fields=["status"], name="notificatio_status_a242db_idx"
                    ),
                    models.Index(
                        fields=["channel"], name="notificatio_channel_e46ef2_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="notificatio_notific_f2898f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["priority"], name="notificatio_priorit_bf8ea0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["is_sent"], name="notificatio_is_sent_254da2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["scheduled_at"], name="notificatio_schedul_21ac35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["user", "is_read"], name="notificatio_user_id_4f3dcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["message_type"], name="notificatio_message_826926_idx"
            ),
        ),
    ]
